services:
  redis:
    container_name: redis_container
    image: redis:8-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - jobber

  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - jobber

  mysql:
    container_name: mysql_container
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=jobber
      - MYSQL_DATABASE=jobber_auth
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_PASSWORD=api
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jobber

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=jobber
      - POSTGRES_DB=jobber_reviews
      - POSTGRES_PASSWORD=api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - jobber

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4.0-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=jobber
      - RABBITMQ_DEFAULT_PASS=api
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jobber

  elasticsearch:
    container_name: elasticsearch_container
    image: elasticsearch:8.17.0
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - jobber

  kibana:
    container_name: kibana_container
    image: kibana:8.17.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_container:9200
    ports:
      - "5601:5601"
    networks:
      - jobber
    depends_on:
      elasticsearch:
        condition: service_healthy
  gateway:
    container_name: gateway_container
    build:
      context: ./server/gateway-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4000:4000"
    env_file: ./server/gateway-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=942421d626948ab10f6809824d95020d
      - JWT_TOKEN=7cca66193669be5de88f6faa69c4ff57
      - NODE_ENV=development
      - SECRET_KEY_ONE=a0dd067a0d146b92cbd01421eb050f1c
      - SECRET_KEY_TWO=16b1c7938bbc482d9793c4f50fff92b1
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://localhost:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - jobber
  notifications:
    container_name: notification_container
    build:
      context: ./server/notification-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4001:4001"
    env_file: ./server/notification-service/.env
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://jobber:api@rabbitmq_container:5672
      - SENDER_EMAIL=eudora.kemmer@ethereal.email
      - SENDER_EMAIL_PASSWORD=GC5xgQhYrfU16489fU
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - jobber

networks:
  jobber:
    driver: bridge

volumes:
  redis_data:
  mongo_data:
  mysql_data:
  postgres_data:
  es_data:
